### PR TITLE
Simplify cod eby better use of dbms_service package

### PR DESCRIPTION
**Pull request by eg90804**
Better use of dbms_service build in package results in simplified code

### CODE REVIEW

**Comment by hajee** [comment]
We've tried this on RAC and it doesn't seem to work.

**Comment by eg90804** [comment]
Bert,

It does work, I used these 2 commands to create a service and activate
in on a RAC 11.2.0.2 without problems.
Closing sessions however only works on the calling instance.

Ed

> We've tried this on RAC and it doesn't seem to work.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hajee/oracle/pull/67#issuecomment-105481830


-- 
Dit is een HTML vrije email / This is an HTML free email.
Zeg NEE tegen de 'slimme' meter.

**Comment by hajee** [comment]
I've looked into this together with @remcovanrijn. [This article](http://surachartopun.com/2009/10/how-to-create-oracle-service-on-11gr2.html?m=1) states that the `DBMS_SERVICE` package doesn't create CRS resources. We want the CRS resources. That's why we use the `SRVRCTL` command to create them. This is also the actual behaviour we saw. 

Did your tests also included checking the CRS?

@remcovanrijn

**Comment by eg90804** [comment]
Did not test it with CRS. If CRS is mandatory, then the old method is
indeed preferred.

Ed

> I've looked into this together with @remcovanrijn. [This
> article](http://surachartopun.com/2009/10/how-to-create-oracle-service-on-11gr2.html?m=1)
> states that the `DBMS_SERVICE` package doesn't create CRS resources. We
> want the CRS resources. That's why we use the `SRVRCTL` command to create
> them. This is also the actual behaviour we saw.
>
> Did your tests also included checking the CRS?
>
> @remcovanrijn
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hajee/oracle/pull/67#issuecomment-105501216


-- 
Dit is een HTML vrije email / This is an HTML free email.
Zeg NEE tegen de 'slimme' meter.

**Pull request closed without merging**
